/* Generates src/lib/columnCase.ts — a lowercase->PascalCase map so the pg shim
   can return result rows with the column casing the app code expects.
   Sources: every [Identifier] in db/full_schema.sql (table/column names) plus
   every `AS <PascalAlias>` in the app's SQL strings under src/. */
import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const names = new Set();

// 1) identifiers from the SQL Server schema (columns, tables, constraints)
const schema = fs.readFileSync(path.join(root, "db/full_schema.sql"), "utf8");
for (const m of schema.matchAll(/\[([A-Za-z_][A-Za-z0-9_]*)\]/g)) names.add(m[1]);

// 2) PascalCase aliases from app SQL (capital "AS Foo"; lowercase "as" = TS casts, skipped)
function walk(dir) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) walk(p);
    else if (/\.tsx?$/.test(e.name)) {
      const src = fs.readFileSync(p, "utf8");
      for (const m of src.matchAll(/\bAS\s+([A-Z][A-Za-z0-9_]*)/g)) names.add(m[1]);
    }
  }
}
walk(path.join(root, "src"));

// 3) build lowercase -> Pascal map; report case collisions
const map = {};
const collisions = [];
for (const n of names) {
  const k = n.toLowerCase();
  if (k === n) continue; // already all-lowercase: pg returns it unchanged
  if (map[k] && map[k] !== n) collisions.push(`${k}: ${map[k]} vs ${n}`);
  else map[k] = n;
}

// Manual overrides for ambiguous casing (only the final-result casing matters):
// `COGS` is read as pnlData.COGS in reports/page.tsx; dashboard's `Cogs` is CTE-only.
const OVERRIDES = { cogs: "COGS" };
Object.assign(map, OVERRIDES);

const sorted = Object.keys(map).sort().reduce((o, k) => ((o[k] = map[k]), o), {});
const out = `// AUTO-GENERATED by db/pg/gen-colmap.mjs — do not edit by hand.
// lowercase Postgres column/alias -> PascalCase the app expects.
export const COLUMN_CASE: Record<string, string> = ${JSON.stringify(sorted, null, 2)};
`;
fs.writeFileSync(path.join(root, "src/lib/columnCase.ts"), out);
console.log(`Wrote src/lib/columnCase.ts with ${Object.keys(sorted).length} entries.`);
if (collisions.length) {
  console.log(`\nCASE COLLISIONS (${collisions.length}) — review:`);
  for (const c of collisions.slice(0, 40)) console.log("  " + c);
}
